package template

import (
	"fmt"
	"io"
	"strconv"
	"sync"
	"time"

	"github.com/OpenListTeam/OpenList/v4/internal/errs"
	"github.com/OpenListTeam/wopan-sdk-go"
)

// maxWoPanFileSize is the maximum file size supported by WoPan.
// It matches the FAT32 maximum single-file size: 4 GiB - 1 byte.
const maxWoPanFileSize = int64(4*1024*1024*1024 - 1)

var (
	woPanUploadIDMu   sync.Mutex
	woPanLastUploadID int64
)

// nextWoPanUploadID returns a process-wide unique, monotonic millisecond
// timestamp. WoPan uses the request's uniqueId as the upload session key. The
// upstream SDK calls time.Now().UnixMilli() directly, so concurrent uploads can
// receive the same id and overwrite each other's chunks.
func nextWoPanUploadID() string {
	woPanUploadIDMu.Lock()
	defer woPanUploadIDMu.Unlock()

	id := time.Now().UnixMilli()
	if id <= woPanLastUploadID {
		id = woPanLastUploadID + 1
	}
	woPanLastUploadID = id
	return strconv.FormatInt(id, 10)
}

// validateWoPanFileSize rejects files above the WoPan limit. The error wraps
// errs.UploadLimitExceeded so upload pipelines can tell an unsupported file
// size (permanent: retrying cannot succeed) apart from transient failures and
// stop re-uploading the whole file.
func validateWoPanFileSize(name string, size int64) error {
	if size > maxWoPanFileSize {
		return errs.NewErr(errs.UploadLimitExceeded,
			"file %q size %d exceeds WoPan maximum file size of %d bytes (4 GiB)",
			name, size, maxWoPanFileSize,
		)
	}
	return nil
}

// upload2C is a local copy of wopan-sdk-go's Upload2C with one important
// difference: uniqueId is generated by nextWoPanUploadID instead of
// time.Now().UnixMilli(). The latter collides for concurrent uploads and makes
// WoPan mix chunks from different files. The SDK does not expose a way to pass
// a caller-provided uniqueId.
func (d *Wopan) upload2C(spaceType string, file wopan.Upload2CFile, targetDirID string, familyID string, opt wopan.Upload2COption) (string, error) {
	client := d.client
	zoneURL := wopan.DefaultZoneURL
	if client.ZoneURL != "" {
		zoneURL = client.ZoneURL
	}

	accessToken, _ := client.GetToken()
	batchNo := time.Now().Format("20060102150405")
	fileInfo := wopan.Json{
		"spaceType":   spaceType,
		"directoryId": targetDirID,
		"batchNo":     batchNo,
		"fileName":    file.Name,
		"fileSize":    file.Size,
		"fileType":    client.GetFileType(file.Name),
	}
	if spaceType == wopan.SpaceTypeFamily {
		fileInfo["familyId"] = familyID
	}
	fileInfoStr, err := client.EncryptParam(wopan.ChannelWoHome, fileInfo)
	if err != nil {
		return "", err
	}

	uploadURL := zoneURL + "/openapi/client/" + wopan.KeyUpload2C
	totalPart := file.Size / wopan.DefaultPartSize
	if totalPart == 0 {
		totalPart = 1
	}
	formData := map[string]string{
		"uniqueId":    nextWoPanUploadID(),
		"accessToken": accessToken,
		"fileName":    file.Name,
		"psToken":     "undefined",
		"fileSize":    strconv.FormatInt(file.Size, 10),
		"totalPart":   strconv.FormatInt(totalPart, 10),
		"channel":     wopan.ChannelWoCloud,
		"directoryId": targetDirID,
		"fileInfo":    fileInfoStr,
	}

	var fid string
	var finishedSize int64
	for partIndex := int64(1); partIndex <= totalPart; partIndex++ {
		if opt.Ctx != nil {
			select {
			case <-opt.Ctx.Done():
				return "", opt.Ctx.Err()
			default:
			}
		}

		partSize := wopan.DefaultPartSize
		if partIndex == totalPart {
			partSize = file.Size - finishedSize
		}
		formData["partSize"] = strconv.FormatInt(partSize, 10)
		formData["partIndex"] = strconv.FormatInt(partIndex, 10)

		var resp wopan.Upload2CResp
		req := client.NewRequest().
			SetResult(&resp).
			ForceContentType("application/json;charset=UTF-8").
			SetHeaders(map[string]string{
				"Origin":     "https://pan.wo.cn",
				"Referer":    "https://pan.wo.cn/",
				"User-Agent": wopan.DefaultUA,
			}).
			SetMultipartFormData(formData).
			SetMultipartField("file", file.Name, file.ContentType, io.LimitReader(file.Content, partSize))
		if opt.Ctx != nil {
			req.SetContext(opt.Ctx)
		}

		res, err := req.Post(uploadURL)
		if err != nil {
			return "", err
		}
		if res.IsError() {
			return "", fmt.Errorf("partIndex: %d, failed to upload2C with http status: %d, body: %s", partIndex, res.StatusCode(), res.String())
		}
		if resp.Code != "0000" {
			return "", fmt.Errorf("partIndex: %d, failed to upload2C with code: %s, msg: %s", partIndex, resp.Code, resp.Msg)
		}
		if resp.Data.Fid != "" {
			fid = resp.Data.Fid
		}
		finishedSize += partSize
		if opt.OnProgress != nil && file.Size > 0 {
			opt.OnProgress(finishedSize, file.Size)
		}
	}
	return fid, nil
}
